/* Approved example (Brickell Honda, 09/2026): quality bar for depth, voice and structure. */
module.exports = {
  dealer: 'brickell-honda',
  dept: 'sales',
  slug: 'honda-trade-in-value-miami-guide',
  path: '/honda-trade-in-value-miami-guide',
  title: 'Honda Trade-In Value in Miami: How It Is Set and Raised',
  ogTitle: 'How Miami Dealers Value a Honda Trade-In, and How to Raise the Number',
  meta: 'How Miami dealers set a Honda trade-in value: KBB ranges, instant offers, appraisals, loan payoff and Florida sales tax, plus steps to raise your number.',
  focus: 'Honda trade-in value Miami',
  keywords: ['Honda trade-in value Miami', 'trade in my Honda Miami', 'how do dealers determine trade-in value', 'how to increase trade-in value', 'KBB Instant Cash Offer Miami', 'trade in car with loan Florida', 'Florida sales tax trade-in credit', 'Honda appraisal Miami'],
  datePublished: '2026-09-28',
  dateModified: '2026-09-28',
  updatedLabel: '09/28/2026',
  eyebrow: 'Honda Buying Guide · Miami',
  section: 'Buying and Selling',
  crumbs: [{ n: 'Value Your Trade', u: '/value-your-trade' }],
  crumbTitle: 'How Miami Dealers Value a Honda Trade-In',
  h1: 'How Miami Dealers Value a Honda Trade-In, and How to Raise the Number',
  dek: 'Your Honda trade-in value in Miami comes from market data, the car\'s condition and history, and the cost to get it ready to sell. Here is how that number is built, what each online tool gives you, and the steps that help you get a fair result.',
  hero: 'IMG_B_HERO',
  banned: ['\\$\\s?\\d', 'top[- ]dollar', 'limited time', 'act now', 'highest', 'beat any', 'lease-return'],
  allowPhrases: ['values are not guaranteed'],
  images: {
    IMG_B_HERO: { apollo: '717450', alt: 'Traffic on the MacArthur Causeway between downtown Miami and Miami Beach', w: 5632, h: 3755, desc: 'Miami road scene: traffic on the MacArthur Causeway with the downtown skyline, daylight, wide landscape' },
    IMG_B_INSPECT: { apollo: '717465', alt: 'Technician with a clipboard inspecting a car\'s condition in a service bay', w: 6000, h: 4000, desc: 'Technician with a clipboard walking around a car in a service bay (appraisal / inspection)' },
    IMG_B_REVIEW: { apollo: '717458', alt: 'Honda team member reviewing paperwork with a customer beside a Honda Ridgeline', w: 1024, h: 683, desc: 'Honda team member reviewing paperwork with a customer beside a Honda Ridgeline' },
    IMG_B_KEYS: { apollo: '717457', alt: 'Customer receiving keys beside a Honda Ridgeline', w: 1024, h: 683, desc: 'Close moment of a customer receiving keys beside a Honda Ridgeline' },
    IMG_B_SERVICE: { apollo: '717448', alt: 'Technician testing a vehicle under the hood with a diagnostic tester', w: 1024, h: 767, desc: 'Technician testing a vehicle under the hood with a handheld diagnostic tester' },
  },
  glance: [
    '<strong>Three different numbers.</strong> A KBB Trade-In Range is an estimate. A KBB Instant Cash Offer is an offer to buy, pending inspection. An in-person appraisal looks at your actual car.',
    '<strong>Condition and history matter.</strong> Appraisal tools weigh mileage, options, condition, history, local demand and the cost to get a car ready to sell.',
    '<strong>A loan is not a dealbreaker.</strong> Florida lets you trade a financed car to a licensed dealer. The dealer has 10 days to satisfy the lien before reselling the car.',
    '<strong>A trade can lower your sales tax.</strong> In a single transaction, Florida taxes the new vehicle\'s price less the trade-in credit.',
  ],
  blocks: [
    { t: 'h2', id: 'how-valued', toc: 'How the number is built', text: 'How do Miami dealers decide what your Honda trade-in is worth?' },
    { t: 'p', html: '<strong>Honda trade-in value in Miami starts from market data for your exact car. It then adjusts for condition, history and reconditioning cost.</strong>' },
    { t: 'p', html: 'Kelley Blue Book says its values use large amounts of data, including actual transactions. KBB then adjusts for local market conditions and seasonal trends. Its values reflect both wholesale and retail sales and are updated at least weekly. Your year, trim, options and mileage set the starting point.' },
    { t: 'p', html: 'The car in front of the appraiser then moves that number. The FTC notes that, with rare exceptions, the older a car gets, the less it is worth. Accidents, repairs or other damage can reduce its value further. Appraisal tools used by dealers can also factor in diagnostic issues and reconditioning costs.' },
    { t: 'stats', items: [
      { n: '7 days', l: 'How long KBB says an Instant Cash Offer is valid, pending inspection. Not all vehicles are eligible.' },
      { n: '10 days', l: 'Time Florida gives a dealer to satisfy the lien on a financed trade-in before reselling it' },
      { n: '50 miles', l: 'Added mileage that KBB says may trigger an Instant Cash Offer recalculation' },
    ] },
    { t: 'p', html: 'At Brickell Honda, our team says it considers more than year, make, model and trim. Condition, mileage, vehicle history and what sells in South Florida all factor in, and a person reviews the car, not just software. See how the process works on our <a href="/sell-your-car-miami-fl">sell your car in Miami</a> page.' },

    { t: 'h2', id: 'three-numbers', toc: 'Range, instant offer or appraisal?', text: 'What is the difference between a KBB Trade-In Range, an Instant Cash Offer and an appraisal?' },
    { t: 'p', html: '<strong>The range is an estimate. The Instant Cash Offer is an offer to buy that still needs an inspection. The appraisal is a dealer looking at your actual car.</strong>' },
    { t: 'p', html: 'All three are useful, but they answer different questions. Knowing which one you hold makes the conversation at the desk simpler.' },
    { t: 'table', caption: 'Three trade-in numbers and where they come from', head: ['Number', 'What it is', 'Where to get it', 'What to know'], rows: [
      ['KBB Trade-In Range', 'KBB\'s estimate of what a consumer can expect to receive this week when trading in at a dealer', 'Our <a href="/value-your-trade">Value Your Trade</a> online tool', 'An estimate, not an offer. KBB notes every dealer is different and values are not guaranteed'],
      ['KBB Instant Cash Offer', 'An offer to buy your car, redeemable at participating dealers', '<a href="/kbb-ico">Instant Cash Offer</a> page (a Kelley Blue Book program)', 'Valid for 7 days, pending inspection. Not all vehicles are eligible, and it may be less than the KBB Trade-In Value or Range'],
      ['In-person appraisal', 'An appraiser walks the vehicle, checks the history and confirms its condition', 'At 690 SW 8th St', 'Based on your actual car. Ask how long the figure stays valid and whether a mileage limit applies'],
    ], note: 'Tool descriptions from Kelley Blue Book and Brickell Honda\'s own pages, reviewed 09/28/2026. Program terms can change.' },
    { t: 'p', html: 'KBB also explains why an Instant Cash Offer can move. During the inspection, the dealer checks the interior and exterior and may test drive the car. If the car does not match your online description, the offer may be raised or lowered. Adding more than 50 miles or a change in condition can also trigger a recalculation.' },

    { t: 'h2', id: 'what-they-check', toc: 'What an appraiser checks', text: 'What does an appraiser look at on your Honda?' },
    { t: 'p', html: '<strong>Condition inside and out, mileage, options, history, keys and accessories, and any sign of mechanical or water trouble.</strong>' },
    { t: 'p', html: 'The same checklist applies whether you start online or walk in, because every online number ends with someone looking at the car.' },
    { t: 'fig', img: 'IMG_B_INSPECT', caption: 'An appraisal confirms the condition you described, inside and out.' },
    { t: 'list', check: true, items: [
      '<strong>Exterior and interior condition.</strong> KBB\'s inspection is a visual check of both, and it may include a test drive.',
      '<strong>Mileage and options.</strong> KBB\'s offer tool weighs mechanical condition, options, mileage, year, make and model.',
      '<strong>History.</strong> The FTC notes a history report may list accidents and flood damage, but typically will not list mechanical problems. That is why the physical inspection still matters.',
      '<strong>Keys, remotes and manuals.</strong> KBB asks sellers to bring all of them. Our team notes that a missing second key affects the value.',
      '<strong>Diagnostics and reconditioning.</strong> Dealer appraisal tools can factor in diagnostic issues and what it costs to make the car ready for the next owner.',
    ] },
    { t: 'p', html: 'Market factors sit outside your control. KBB lists supply and demand, historical trends, regional differences and local comparable sales among its inputs. What you can control is covered next.' },

    { t: 'h2', id: 'raise-the-number', toc: 'How to raise your number', text: 'How can you raise your Honda\'s trade-in number?' },
    { t: 'p', html: '<strong>Know your numbers first, make the car easy to verify, and keep the trade separate from the price of your next car.</strong>' },
    { t: 'p', html: 'None of these steps costs much, and each one is in your control.' },
    { t: 'steps', items: [
      { h: 'Research before you negotiate.', html: 'The FTC advises finding out what your current vehicle is worth before you negotiate a new one. Start with our <a href="/value-your-trade">online trade value tool</a> and a <a href="/kbb-ico">KBB Instant Cash Offer</a>.' },
      { h: 'Compare more than one estimate.', html: 'The CFPB says you can get trade-in estimates from multiple dealerships and negotiate your trade-in value.' },
      { h: 'Negotiate the price and the trade separately.', html: 'The FTC suggests waiting to discuss a trade-in until after you have negotiated the price of the new car.' },
      { h: 'Bring your records.', html: 'NHTSA suggests comparing odometer mileage with maintenance or inspection records, so records help an appraiser confirm your car\'s history. Our team says documented maintenance can move the number.' },
      { h: 'Bring every key and remote.', html: 'Include manuals and accessories, as KBB asks.' },
      { h: 'Check open recalls.', html: 'Look up your VIN or plate on <a href="/honda-recalls">Honda recalls</a> or <a href="https://www.nhtsa.gov/recalls" rel="noopener">NHTSA</a>. KBB lists unresolved recalls as one reason a car may not qualify for an Instant Cash Offer. Recall repairs can be scheduled through our <a href="/scheduleservice">service department</a>.' },
      { h: 'Ask before paying for repairs.', html: 'Our team recommends getting an estimate of the trade-in before and after repairs, so you can decide if a fix is worth it.' },
    ] },
    { t: 'pair', items: [
      { img: 'IMG_B_KEYS', caption: 'Bring every key and remote. Our team notes that a missing second key affects the value.' },
      { img: 'IMG_B_SERVICE', caption: 'Service records help an appraiser confirm your car\'s history and mileage.' },
    ] },
    { t: 'p', html: 'Under Florida law, a trade-in can be reappraised after the contract if it is later damaged or parts or accessories are removed. Deliver the car in the condition it was appraised, with everything that came with it.' },
    { t: 'cta', text: 'Want a starting number before you visit?', label: 'Value Your Trade', href: '/value-your-trade' },

    { t: 'h2', id: 'miami', toc: 'Miami sun, humidity and flood history', text: 'How do Miami sun, humidity and flood history affect a trade-in?' },
    { t: 'p', html: '<strong>Appraisers look closely at cosmetic and interior condition. In Florida, they also commonly look for signs of water exposure.</strong>' },
    { t: 'p', html: 'Daily sun and humidity are part of driving in Miami. Keep the car washed, shaded or garaged when you can, and keep the cabin clean and dry. Appraisers look at cosmetic and interior condition.' },
    { t: 'callout', label: 'Florida and flood titles', html: 'The Florida Department of Highway Safety and Motor Vehicles (FLHSMV) notes that flooding is one of Florida\'s most frequent hazards. Florida law requires flood damage to be marked conspicuously on the title, and dealers must disclose branded titles in writing. FLHSMV also warns that a flood-damaged car from another state can be sold in Florida with a clean title.' },
    { t: 'p', html: 'Appraisers commonly look for the signs FLHSMV lists. These include a musty smell or heavy air freshener, and a waterline or mud in the glove box, under the dash or in the trunk. Another sign is rust that looks out of place for the car\'s age and location. You can check your own title for brands with the FLHSMV Motor Vehicle Information Check or the national NMVTIS database at vehiclehistory.gov.' },

    { t: 'h2', id: 'loan', toc: 'Trading in with a loan', text: 'Can you trade in a Honda that is not paid off in Florida?' },
    { t: 'p', html: '<strong>Yes. FLHSMV says you can trade in a vehicle with an existing lien at a dealership. The dealer has 10 days to satisfy the lien before reselling the car.</strong>' },
    { t: 'p', html: 'FLHSMV adds that you do not need to request a paper title before trading with a licensed Florida dealer. Ask your lender for a payoff quote before you visit. The CFPB notes the payoff amount can differ from your statement balance because of how interest is calculated, fees or other reasons. On our <a href="/sell-your-car-miami-fl">sell your car</a> page, our team says it works directly with your lender on the payoff.' },
    { t: 'p', html: 'After the deal, the CFPB suggests waiting one week and then contacting your old lender to confirm the loan was paid off. If you are planning your next payment, see our <a href="/how-much-car-can-i-afford">how much car can I afford</a> guide and the <a href="/getfinancing">online financing application</a>.' },

    { t: 'h2', id: 'negative-equity', toc: 'If you owe more than it is worth', text: 'What happens if you owe more on your Honda than it is worth?' },
    { t: 'p', html: '<strong>That gap is called negative equity. It does not disappear; it has to be paid off or added to your next loan.</strong>' },
    { t: 'p', html: 'The FTC explains that some dealers roll negative equity into the new car loan, so you still end up paying it. It can be added to the new loan, taken from your down payment, or both. The CFPB adds that rolling a balance in makes the new loan more expensive. It also increases the interest you pay over the life of the loan.' },
    { t: 'list', items: [
      '<strong>Read the disclosures.</strong> The FTC says the dealer must give you credit cost disclosures before you sign. Check the down payment and the amount financed.',
      '<strong>Get promises in writing.</strong> The FTC advises making sure any oral promises are included in the contract.',
      '<strong>Keep the term as short as you can afford,</strong> especially if negative equity is rolled into the new loan, as the FTC recommends.',
      '<strong>Know one rule.</strong> The FTC says that if a dealer tells you it will pay off your car itself but really rolls the cost into your loan, that is illegal.',
    ] },
    { t: 'p', html: 'Our team says that if you buy from us, the gap may be able to roll into your new financing, subject to lender approval. If you sell outright, they will show you the difference so you can settle it directly. You can read the FTC\'s full guide, <a href="https://consumer.ftc.gov/articles/auto-trade-ins-and-negative-equity-when-you-owe-more-your-car-worth" rel="noopener">Auto Trade-Ins and Negative Equity</a>.' },

    { t: 'h2', id: 'sales-tax', toc: 'Florida sales tax and trade-ins', text: 'Does trading in your Honda lower your Florida sales tax?' },
    { t: 'p', html: '<strong>Yes, when it happens in a single transaction. Florida taxes the new vehicle\'s sales price less the credit for the vehicle taken in trade.</strong>' },
    { t: 'p', html: 'That rule comes from Florida Statutes section 212.09. The Florida Department of Revenue says a registered motor vehicle dealer may deduct a trade-in allowance from the taxable sales price. The trade must be part of the same sale. Selling your car outright, with no purchase in the same transaction, does not create a trade-in credit. Tax treatment depends on your specific transaction and current Florida law. Your final documents govern, so ask a tax professional about your own situation.' },
    { t: 'fig', prose: true, img: 'IMG_B_REVIEW', caption: 'Check the trade-in figure, the down payment and the amount financed on the contract before you sign.' },

    { t: 'h2', id: 'what-to-bring', toc: 'What to bring', text: 'What should you bring to trade in your Honda at Brickell Honda?' },
    { t: 'p', html: '<strong>Your car, every key, your title or loan details, registration, a photo ID, and any service records.</strong>' },
    { t: 'p', html: 'This list combines KBB\'s Instant Cash Offer checklist with what our team asks for at the appraisal.' },
    { t: 'list', check: true, items: [
      '<strong>Title,</strong> or your lender\'s information if the car is financed. If it is leased, check with the leasing company first.',
      '<strong>Current registration.</strong>',
      '<strong>Valid government photo ID</strong> for every person on the title, as our team asks.',
      '<strong>All keys, keyless remotes and manuals.</strong>',
      '<strong>Service and repair records,</strong> if you have them.',
      '<strong>Payoff information</strong> from your lender, if there is a loan.',
    ] },
    { t: 'p', html: 'Both you and the buyer acknowledge the odometer reading on the title, as federal law and FLHSMV require. Then browse <a href="/inventory/new">new Honda inventory</a>, such as the <a href="/inventory/new/honda/cr-v">Honda CR-V</a> and <a href="/inventory/new/honda/civic-sedan">Civic Sedan</a>. You can also see our <a href="/inventory/cpo">Honda Certified Pre-Owned</a> selection and <a href="/specials/vehicle-specials">current vehicle specials</a>. Drivers come to SW 8th Street from nearby <a href="/coral-gables-fl-honda-dealer">Coral Gables</a>, <a href="/coconut-grove-fl-honda-dealer">Coconut Grove</a> and <a href="/key-biscayne-fl-honda-dealership">Key Biscayne</a>.' },
  ],
  faqTitle: 'Trade-in questions, answered',
  faqIntro: 'Short answers to common questions about trading in or selling a car in Miami.',
  faqCall: 'Questions about your trade? Call our sales team at {{PHONE}}.',
  faq: [
    { q: 'Is a KBB Instant Cash Offer a firm price?', a: 'It is an offer to buy, but it depends on an inspection. KBB says the offer is valid for 7 days at participating dealers, pending inspection. It may be raised or lowered if the car does not match your online description. KBB also notes the offer may be less than the Kelley Blue Book Trade-In Value or Range, and not all vehicles are eligible.' },
    { q: 'Do I need my paper title to trade in a financed car in Florida?', a: 'No. FLHSMV says it is not necessary to request a paper title before trading a vehicle with a licensed Florida dealer. You can trade a car with an existing lien, and the dealer has 10 days to satisfy the lien before reselling it. Bring your lender\'s information and a current payoff quote.' },
    { q: 'Can I sell my car to Brickell Honda without buying one?', a: 'Yes. Our team says no purchase is required to sell your car to us, and we buy all makes. Florida\'s sales tax trade-in credit only applies when the trade is part of a purchase in the same transaction. An outright sale does not create that credit.' },
    { q: 'Do open recalls affect trading in my car?', a: 'They can affect an instant offer. KBB lists unresolved recalls among the reasons a vehicle may not qualify for an Instant Cash Offer. NHTSA\'s recall lookup shows recalls that still need repair, though it may not show very recent recalls or those more than 15 years old. Schedule any open repair before you trade.' },
    { q: 'Should I fix dents or damage before I trade in?', a: 'Ask first. Our team recommends getting an estimate of the trade-in before and after repairs, so you can see whether a repair is worth the cost. Also avoid removing parts or accessories after the appraisal. Florida law allows a trade-in to be reappraised if parts are removed.' },
    { q: 'Can I trade in a car owned by my business?', a: 'Yes, with the right paperwork. Our team says business-owned vehicles need written authorization from a company officer. Bring that authorization along with the title or lender information, the registration and a valid photo ID. Ask our sales team in advance whether anything else is needed for your company\'s vehicle.' },
    { q: 'How is selling privately different from trading in Florida?', a: 'In a private sale, FLHSMV says the seller completes the title transfer, removes the plate and files a Notice of Sale. A private sale is not legal while a lien exists. Trading in with a licensed dealer lets the dealer handle the lien. A trade in the same transaction can also reduce the sales tax you pay.' },
    { q: 'Can I trade in a leased Honda?', a: 'Check with your leasing company first, as KBB advises for leased cars. Have your plate number, lender name, lease account number, remaining payments and current mileage ready. Our sales team can review your options with you and explain what the leasing company needs.' },
    { q: 'Can I handle my trade-in in Spanish?', a: 'Yes. Our team says the appraisal, paperwork and payoff can be explained in Spanish from start to finish. Se habla español. Call our sales team or visit us at 690 SW 8th St to start your appraisal in Spanish or English.' },
    { q: 'What is the odometer disclosure when I trade in?', a: 'Federal law requires the seller to give a written disclosure of the mileage on the title when ownership changes. FLHSMV says both the buyer and the seller must acknowledge odometer disclosures on title transactions. Your maintenance records can also help confirm the mileage history.' },
  ],
  dealerSection: {
    eyebrow: 'Visit us in Miami',
    h: 'Get your Honda appraised on SW 8th Street',
    p: 'Our sales team is at 690 SW 8th St in Miami. Start online with the trade value tool, then bring the car in so an appraiser can review it and give you a figure in person. Brickell Honda is a proud member of the Murgado Automotive Group.',
  },
  closer: {
    h: 'Start with a number. Finish with an appraisal.',
    p: 'Get your KBB Trade-In Range online, then bring your Honda to SW 8th Street for an in-person appraisal. Our team says no purchase is required.',
    secondary: { label: 'Shop New Hondas', href: '/inventory/new' },
  },
  related: [
    { k: 'Sell or trade', t: 'Sell your car in Miami', d: 'How our appraisal works, what to bring and how payoff is handled.', href: '/sell-your-car-miami-fl' },
    { k: 'Instant offer', t: 'KBB Instant Cash Offer', d: 'A Kelley Blue Book offer to buy your car, pending inspection.', href: '/kbb-ico' },
    { k: 'Financing', t: 'How much car can I afford?', d: 'Plan your next payment before you shop.', href: '/how-much-car-can-i-afford' },
  ],
  fine: 'Sources reviewed 09/28/2026: FTC, "Auto Trade-Ins and Negative Equity" and "Buying a Used Car From a Dealer"; CFPB, "Should I trade in my car if it\'s not paid off?"; Florida Statutes s. 212.09 and s. 501.976 and Florida Department of Revenue brochure GT-800030; FLHSMV selling-a-vehicle and flooded-vehicle advisories; NHTSA recalls and odometer guidance; Kelley Blue Book value and Instant Cash Offer descriptions. Kelley Blue Book does not redeem Offers, purchase vehicles or own/operate Participating Dealers. Dealer inspection required. This page does not state or estimate any trade-in value. Offers and appraisals depend on the individual vehicle and market conditions. Tax treatment depends on your transaction; your final documents govern.',
  about: [{ '@type': 'Thing', name: 'Trade-in' }, { '@type': 'Thing', name: 'Kelley Blue Book Instant Cash Offer' }, { '@type': 'Thing', name: 'Negative equity' }],
  allowedLinks: ['/sell-your-car-miami-fl', '/value-your-trade', '/kbb-ico', '/honda-recalls', '/scheduleservice', '/how-much-car-can-i-afford', '/getfinancing', '/inventory/new', '/inventory/new/honda/cr-v', '/inventory/new/honda/civic-sedan', '/inventory/cpo', '/specials/vehicle-specials', '/coral-gables-fl-honda-dealer', '/coconut-grove-fl-honda-dealer', '/key-biscayne-fl-honda-dealership'],
};
